### ISSUE TITLE
Missing Code For Checking Players Job

### ISSUE THREAD

**Issue by MarcusPlayz517** [Disabled-Coding/dc-adminmenu#11]
**There is missing code to show players job in the menu.**

**Screenshots, Before & After**

![FiveM_b2372_GTAProcess_pgXNXwxh82](https://user-images.githubusercontent.com/100505762/166871026-c2a592ce-68f4-4df4-b898-643cb8a4a790.jpg)
![FiveM_b2372_GTAProcess_QD3GcHZTWd](https://user-images.githubusercontent.com/100505762/166871030-b7310d30-3b85-4222-a5a0-f8f6bd10923c.jpg)

**Fix**
client > playersmenu.lua > add to line 725.

       local PlayersButton11 = PlayerDetailMenu:AddButton({
        label = Lang:t("label.job").. ': ' ..PlayerDetails.job,
        description = Lang:t("desc.player_info")
    })

**Comment by ChatDisabled** [comment]
Wow someone who actually reads the code. When I get on my PC I'll add this indeed. Somehow forgot it.

**Comment by ChatDisabled** [comment]
gotta love qb-input innit

**Comment by ChatDisabled** [comment]
Will both be pushed somewhere end this week. Thanks for the headsup. Btw suggestions are welcome as well!
https://github.com/Disabled-Coding/dc-adminmenu/commit/064f87e4420ec0dae3ab7b4ef0cdb8745f89aa27
https://github.com/Disabled-Coding/dc-adminmenu/commit/8b011390352a995f3d376d659a4f8e2458c400f8

**Comment by MarcusPlayz517** [comment]
sweet as
