### ISSUE TITLE
Revive Not working

### ISSUE THREAD

**Issue by DarrianJCairns** [Disabled-Coding/dc-adminmenu#17]
**Describe the bug**
Revive option sadly doesnt work for players,

Kill/Revive/Freeze doesnt work

**Comment by DarrianJCairns** [comment]
> Follow the NetEvents, see if you even have these NetEvents in the first place and don't have an edited core. These also don't work when trying to apply them to someone of the same rank or higher. That's normal behaviour.

Hey, it's a base Core file.. QB adminmenu worked so I assumed this would've worked fine... I can revive myself but normal players nope.. aswell as the other options

**Comment by ChatDisabled** [comment]
I've been busy and still looking into it. Still haven't found anyone else with this problem. What "other options" are having problems and again are you sure you ain't trying it on someone else with the same or higher rank?

**Comment by ChatDisabled** [comment]
I can't find anyone else with these problems except you man. Think about what could possibly be going wrong. I already told you the expected behaviour behind it.
