### ISSUE TITLE
Vehicle Menu doesn't open 

### ISSUE THREAD

**Issue by SullyR9** [Disabled-Coding/dc-adminmenu#18]
When I'm in a car and hit the vehicle upgrade/tune menu option, it just exits admin menu and nothing happens

**Comment by ChatDisabled** [comment]
Update both qb-customs and qb-radialmenu

**Comment by ChatDisabled** [comment]
Seeing that you also had an older core indeed update both your customs and radialmenu. Closing this one in favour of using #19
