### ISSUE TITLE
Getting kicked when using /admin

### ISSUE THREAD

**Issue by SullyR9** [Disabled-Coding/dc-adminmenu#19]
Having an issue with one admin, where I've tried setting them to both AdminmenuGod and AdminmenuAdmin and they get kicked when using /admin. They have permissions in server.cfg and also in database

**Comment by ChatDisabled** [comment]
Remove the "adminmenu." part in front of the "god" and "admin" in your config.lua in events and permorder

**Comment by SullyR9** [comment]
> Remove the "adminmenu." part in front of the "god" and "admin" in your config.lua in events and permorder

So just have it as licence.xxxxx admin?

**Comment by SullyR9** [comment]
Ah got you! And then in perms cfg do I need to do anything with that? Sorry to be a bother, still fairly new to all of this so really appreciate your help!!

**Comment by ChatDisabled** [comment]
Nope, only thing that won't work for you right now is adding or removing perms through the menu since I still need to make that backwards compatibel

**Comment by SullyR9** [comment]
Awesome! Thanks so much for the help. really appreciate it! And all our admin team love the menu too!!

**Comment by SullyR9** [comment]
Just waiting on the person who it was happening to enter the server but will let you know as soon as he does!

**Comment by ChatDisabled** [comment]
@SullyR9 update?

**Comment by SullyR9** [comment]
Soory, he only logged in today, works perfectly!! Thanks for the help!!!
