### ISSUE TITLE
Spawn Weapons with specific Ammo and individual Ammo items

### ISSUE THREAD

**Issue by TheiLLeniumStudios** [Disabled-Coding/dc-adminmenu#20]
**Does your feature actually have any sense inside of an admin menu?**
It does. Saves a lot of typing and time when you want to give someone a gun with X ammo

**Is your feature request related to a problem? Please describe.**
No

**Describe alternatives you've considered**

**Additional context**

**Comment by ChatDisabled** [comment]
Wow the one and only @TheiLLeniumStudios. Added to the backlog. Hope I don't forget it like all the other features 🦀.

**Comment by TheiLLeniumStudios** [comment]
> Wow the one and only @TheiLLeniumStudios. Added to the backlog. Hope I don't forget it like all the other features 🦀.

Lmao. You know me? :D 
Anyways, I might send a PR for this over the weekend if I get some free time. Great resource btw, love the additions!

**Comment by ChatDisabled** [comment]
Ahw Linter guy doesn't know me. Now I'm sad 😢. You prob already haven seen me around before but haven't realised it yet.

> I might send a PR for this over the weekend if I get some free time
Not if I get free time first >:)

**Comment by TheiLLeniumStudios** [comment]
> Ahw Linter guy doesn't know me. Now I'm sad 😢. You prob already haven seen me around before but haven't realised it yet.
> 
> > I might send a PR for this over the weekend if I get some free time
> > Not if I get free time first >:)

Ohh yeah right, I think I've come across your name before, in LJ's discord 😃 Didn't actually pay attention to the name when creating the ticket, apologies haha.

I would like to see you use the linter for your resources though. Let me know if you need any help with setting that stuff up. Will gladly help you!

**Comment by TheiLLeniumStudios** [comment]
@ChatDisabled just a reference of what could be added to the Weapon sub-menu:
![image](https://user-images.githubusercontent.com/104288623/168374359-b8bdc942-b7c3-4b03-828d-6e4ac632af5f.png)
![image](https://user-images.githubusercontent.com/104288623/168374412-a52d03a0-4739-4a9e-b94c-b68e77d7e5e8.png)

These are images from hyipe-debug menu which is a paid release and its not optimized at all, and the fact that it requires a separate resource, I just don't like it

**Comment by ChatDisabled** [comment]
Well mine is also already at 4+ dependencies so 😂. Removing them of course is easy with exceptions from input and menu. But normal users will have trouble with it. Input could be replaced though by the native GTA input. But really thanks I'm always pushing people to give me more suggestions! Will def add the top part of adding all sets of a wep category.

**Comment by TheiLLeniumStudios** [comment]
@ChatDisabled everyone has those dependencies in their qb-core based servers, there's nothing new that you're adding, as a dependency, so all good 😃

**Comment by ChatDisabled** [comment]
Backwards compatability is a pain though

**Comment by TheiLLeniumStudios** [comment]
@ChatDisabled I agree. But honestly, you shouldn't be providing backwards compatibility indefinitely. Server owners / devs need to upgrade to the latest core at the very least, and also the main scripts at some point. Otherwise you'll be investing more on trying to fix compatibility issues rather than making the resource more feature rich and stable. If I would release something that depends on qb-core resources, I'd just be supporting the qb-core framework no more than 3 months old. This does limit the amount of users using the resource, but we have to make some sacrifices to ensure the sanity of the code / resource and ourselves too. We can't make everyone happy 😆 Its just an opinion, we can agree to disagree on this though

**Comment by ChatDisabled** [comment]
Not done yet but https://github.com/Disabled-Coding/dc-adminmenu/commit/f50ba240cfefae44629061b3f0688e97916c4687

More will be added

**Comment by TheiLLeniumStudios** [comment]
@ChatDisabled Great start. Can you add safety checks for `qb-admin:server:giveallweapons` event? Maybe check if the source has admin / god permissions? Otherwise it could be a potential event for cheaters to abuse and get all weapons

**Comment by TheiLLeniumStudios** [comment]
Nevermind, you have the check 😃
