### ISSUE TITLE
How do i add myself?

### ISSUE THREAD

**Issue by AndreasFromDanmark** [Disabled-Coding/dc-adminmenu#22]
Its just kicking my out of the server after i type /admin in chat ingame

![image](https://user-images.githubusercontent.com/35656492/169681397-98b80311-1f62-4c3a-ae18-2d263502b6c4.png)

**Comment by lordfalcon22** [comment]
Look at the green writing below bud, add your identifiers for the admin role

**Comment by AndreasFromDanmark** [comment]
I have tried my FiveM id and steam64, and its still kicking me
