### ISSUE TITLE
nil value (radiochannel)

### ISSUE THREAD

**Issue by Sulb0** [Disabled-Coding/dc-adminmenu#23]
Hi, I keep getting a 'radiochannel' error whenever I click on a player
![image](https://user-images.githubusercontent.com/99930543/169893619-4b983004-2b3c-40cd-bc05-97cef82cb205.png)

**Comment by ChatDisabled** [comment]
Simply means they haven't changed their radio channel yet and are still on 0. Test it with yourself. Otherwise you might have an adapted PMA-Voice resource or outdated one. Preferably just update to the newest.

**Comment by SullyR9** [comment]
Ahh right, got ya. For some reason when we click on a player that isn't an admin, sometimes the full list of stats like money, stress etc don't pop up, so thought that was causing the issue

**Comment by ChatDisabled** [comment]
If the whole list doesn't pop that's certainly another problem. Tell me whenever this happens. The other 'problem' will be fixed somewhere in the future whenever I merge into main. https://github.com/Disabled-Coding/dc-adminmenu/commit/fb002494b5a52706b6ad87a21e90dc766d3b3850

**Comment by SullyR9** [comment]
Yeah so it happens most times. Like it works when I do it over a member of staff/admin, and then very rarely over a normal player, but most times it only comes up with the 3 starting options like General.
