### ISSUE TITLE
[FEATURE] more permissions

### ISSUE THREAD

**Issue by IllInuz** [Disabled-Coding/dc-adminmenu#35]
**Does your feature actually have any sense inside of an admin menu?**
yes, its already there.

**Is your feature request related to a problem? Please describe.**
Add more permissions for the godmode, invisible etc.

**Describe alternatives you've considered**
Removal of it.

**Additional context**
May not want the permission available to all individual admins, make it permission based instead

**Comment by ChatDisabled** [comment]
Technically fixed / more will be added in the future
