### ISSUE TITLE
[ISSUE] Banning doesn't kick a player + unable to index a nil value 'Discord'

### ISSUE THREAD

**Issue by FizzGamingJR** [Disabled-Coding/dc-adminmenu#38]
**Describe the bug**
Upon banning a person they do not get kicked from the server, and we also receive a message in F8 console saying that it is unable to index a nil value 'Discord'.

**To Reproduce**
1. Type /admin
2. Navigate to Player Management.
3. Ban a person.

**Expected behavior**
I believe that after banning a person they are meant to get kicked from the server? and I also assume that it's meant to provide a discord link to appeal, but something isn't working somewhere.
I've tried adding and removing the https:// on the discord link in qb-core > config but nothing seems to fix it.

**Additional context**
I am able to kick people without any issues, but when we have the casual griefers who join and spam all kinds in global chat it is a matter of seconds/minutes lost after typing the reason in the ban section, and then having to do the same in the Kick section.

**Comment by Loc0** [comment]
server > main.lua > line 202 >
DropPlayer(target, Lang:t("info.kicked_server") .. ':\n' .. reason .. '\n\n' .. Lang:t("info.check_discord") .. QBCore.Config.Server.Discord)

Try that

**Comment by ChatDisabled** [comment]
Fixed with upcoming commit
