### ISSUE TITLE
Game quites when type /admin

### ISSUE THREAD

**Issue by Voracious7** [Disabled-Coding/dc-adminmenu#4]
Hey, thanks for providing this to the community! :)

I have straight copy-pasted this into the existing admin menu (not sure if that's what your supposed to do) 
when i type/admin the menu pops up for a second and kicks me from server (saying are you allowed to do that) 

so not sure if there are steps missing? 

thanks
V

**Comment by ChatDisabled** [comment]
Just make absolutely sure you have the proper admin/god permissions. E.g. did you change your server.cfg ace permission from group.god to qbcore.god?

**Comment by stewiehell** [comment]
i same please show mi add ace in server.cfg

**Comment by stewiehell** [comment]
![image](https://user-images.githubusercontent.com/102426823/166587412-660d9905-3d7f-468d-a298-baf34ec563c7.png)

**Comment by ChatDisabled** [comment]
I made this in the meantime. Please tell me if it helps your case. https://github.com/Disabled-Coding/dc-adminmenu#i-get-kicked-while-using-the-command-admin

**Comment by ChatDisabled** [comment]
@Voracious7 @stewiehell Is there anything else? Or can this be closed?

**Comment by stewiehell** [comment]
thanks help <3
