### ISSUE TITLE
[ISSUE] Tune Vehicles doesnt work if your qb-customs uses the radial menu

### ISSUE THREAD

**Issue by Twoxxyy** [Disabled-Coding/dc-adminmenu#43]
**Describe the bug**
Basically, if you have your qb-customs setup to use the F1 menu to access the garage, then the admin menu gives you an error saying @dcadminmenu/client/vehiclemenu.lua:97 and will not allow you to open the tuning menu.

**To Reproduce**
1. Go to Tune vehicles section of the vehicles tab in the admin menu
2. Click on tune vehicle
3. See error (you must have qb-customs config useradial set to true)

**Screenshots | Video**
![adminmenuerror](https://user-images.githubusercontent.com/102333621/187090967-c159f537-b6fb-45d4-872c-882d84220bb6.png)

**Comment by ChatDisabled** [comment]
While true that this happens, this isn't a problem on my part but the behavior on `qb-customs`. Edit yours like the image on line 769.
![image](https://user-images.githubusercontent.com/44729807/187100489-8c6c43b9-1706-4d4f-8246-daa2511d7f9d.png)
