### ISSUE TITLE
Sound not working on self?

### ISSUE THREAD

**Issue by NoobySloth** [Disabled-Coding/dc-adminmenu#6]
When trying to play a sound on self nothing happens but also the menu format of all the sounds goes weird?

![image](https://user-images.githubusercontent.com/6962192/166746721-c5073828-b1b3-40ae-8b41-3ea522e9e9cd.png)

Video is on this link: https://nooby.xyz/nooby/f/urw2i6-04-05-2022.mp4

**Comment by ChatDisabled** [comment]
First it's nice to see someone not complain about the permission and seeing the menu actually work on a live server 😭! But indeed the sound names shouldn't be displayed like that on the same line. Do you have some special path instead of the traditional one like in the picture? It's weird since it also pulled the full path from your server at the top 🤔
![image](https://user-images.githubusercontent.com/44729807/166818676-1eef777e-2b2e-4a30-b6d1-9545cae25cfd.png)

**Comment by NoobySloth** [comment]
> 

Aahah permissions all good here 😎 but this is my path;
![image](https://user-images.githubusercontent.com/6962192/166819264-82d71188-1eac-4ac1-9c53-f88d3603bd55.png)

**Comment by ChatDisabled** [comment]
And I guess this happens all the time?

**Comment by NoobySloth** [comment]
> 

Even had a restart and still showing
![image](https://user-images.githubusercontent.com/6962192/166820077-9d3a7b1e-da50-41e7-a7cd-b8193dc485e7.png)

**Comment by ChatDisabled** [comment]
Would you mind changing the Thread that collects the sound files to
```
CreateThread(function()
    for filename in io.popen('dir "'..SoundPath..'" /b'):lines() do
        Sounds[#Sounds + 1] = filename:match("(.+)%..+$")
    end
end)
```
With `SoundPath` being the location of your sounds like
`'R:/QBCore/txData/QBCoreFramework_66EEE6.base/resources/[standalone]/interact-sound/client/html/sounds'` (in my case)
The var already exists in the config.lua so just change it there and see.

**Comment by NoobySloth** [comment]
> Would you mind changing the Thread that collects the sound files to
> 
> ```
> CreateThread(function()
>     for filename in io.popen('dir "'..SoundPath..'" /b'):lines() do
>         Sounds[#Sounds + 1] = filename:match("(.+)%..+$")
>     end
> end)
> ```
> 
> With `SoundPath` being the location of your sounds like `'R:/QBCore/txData/QBCoreFramework_66EEE6.base/resources/[standalone]/interact-sound/client/html/sounds'` (in my case) The var already exists in the config.lua so just change it there and see.

Done this and still prints the same...
![image](https://user-images.githubusercontent.com/6962192/166824535-8bdd8859-ab17-4639-94ca-58055339df21.png)

**Comment by ChatDisabled** [comment]
Very strange since the expected result is of course this.
![image](https://user-images.githubusercontent.com/44729807/166825480-55302dee-7c57-453d-b3a1-cc6191f277f8.png)

The only thing I can say for now is remove the thread all together and adding the sounds that you want manually yourself like so.
```
Sounds = {
    'airwrench',
    'Alert',
    'alreadyusing'
}
```

I really hope I can find something for this unexpected behaviour of `io.popen` but I doubt it since I just yoinked public code and have limited understanding of it myself. I will keep this posted _if_ in seven hells I do find something.

**Comment by NoobySloth** [comment]
> Very strange since the expected result is of course this. ![image](https://user-images.githubusercontent.com/44729807/166825480-55302dee-7c57-453d-b3a1-cc6191f277f8.png)
> 
> The only thing I can say for now is remove the thread all together and adding the sounds that you want manually yourself like so.
> 
> ```
> Sounds = {
>     'airwrench',
>     'Alert',
>     'alreadyusing'
> }
> ```
> 
> I really hope I can find something for this unexpected behaviour of `io.popen` but I doubt it since I just yoinked public code and have limited understanding of it myself. I will keep this posted _if_ in seven hells I do find something.

Maybe I have to many sounds? I'll make a seperate folder with seperate sounds to test

**Comment by NoobySloth** [comment]
Nope.. that did not work, do i need to update qb-menu?

![image](https://user-images.githubusercontent.com/6962192/166826506-b3282772-cd8c-4bc4-9d13-764728815ad2.png)

**Comment by ChatDisabled** [comment]
Nah just do it manually for now like I said. qb-menu is just displaying the full table of what it pulls on the server side. Unless somehow it does fuck up there? Do you mind simply inserting this print statement and telling me what it prints for you? _Should_ also just be all the file names.
```
CreateThread(function()
    for filename in io.popen('dir "'..SoundPath..'" /b'):lines() do
        print(filename:match("(.+)%..+$"))
        Sounds[#Sounds + 1] = filename:match("(.+)%..+$")
    end
end)
```

**Comment by NoobySloth** [comment]
> Nah just do it manually for now like I said. qb-menu is just displaying the full table of what it pulls on the server side. Unless somehow it does fuck up there? Do you mind simply inserting this print statement and telling me what it prints for you? _Should_ also just be all the file names.
> 
> ```
> CreateThread(function()
>     for filename in io.popen('dir "'..SoundPath..'" /b'):lines() do
>         print(filename:match("(.+)%..+$"))
>         Sounds[#Sounds + 1] = filename:match("(.+)%..+$")
>     end
> end)
> ```

![image](https://user-images.githubusercontent.com/6962192/166827046-f887ecc0-e4d4-49f3-ac0d-7256c07e7aac.png)

**Comment by ChatDisabled** [comment]
Some lovely cat whispered something to me. Is it possible that you have a linux machine running? Mind changing the "dir" part to "ls" then? Should result in `for filename in io.popen('ls "'..SoundPath..'" /b'):lines() do`

**Comment by NoobySloth** [comment]
> 

ahhh yes I am indeed on linux 😂 That looks better
![image](https://user-images.githubusercontent.com/6962192/166828138-142fb4e5-f217-4434-8adb-15c900cce4d1.png)

**Comment by ChatDisabled** [comment]
Not only does it need to look better, does it perform 🤔

**Comment by NoobySloth** [comment]
> 

It did indeed, until i restarted interact-sound to add fart noises 😂 probably need to restart my server but yes, it did indeed work! Thank you :)

**Comment by ChatDisabled** [comment]
My pleasure. Need to keep this one in mind for the next Linux user. Enjoy.

**Comment by NoobySloth** [comment]
Can you just do something like this?

CreateThread(function()
    if Config.Linux then
        for filename in io.popen('ls "'..SoundPath..'" /b'):lines() do
            Sounds[#Sounds + 1] = filename:match("(.+)%..+$")
        end
    else
        local path = GetResourcePath(SoundScriptName)
        local directory = path:gsub('//', '/')..SoundPath
        for filename in io.popen('dir "'..directory..'" /b'):lines() do
            Sounds[#Sounds + 1] = filename:match("(.+)%..+$")
        end
    end
end)

**Comment by ChatDisabled** [comment]
Since you asked https://github.com/Disabled-Coding/dc-adminmenu/commit/718b369aaf228150676920e2ba8b99ebccbbe53a
